from __future__ import annotations

from tohupono.concepts.model import ProofConcept


def _concept(
    concept_id: str,
    display_name: str,
    category: str,
    maturity: str,
    definition: str,
    exact_claim: str,
    subject: str,
    boundary: str,
    evidence: tuple[str, ...],
    procedure: tuple[str, ...],
    failure_conditions: tuple[str, ...],
    limitations: tuple[str, ...],
    capabilities: tuple[str, ...] = (),
    trust: tuple[str, ...] = (),
    privacy: tuple[str, ...] = (),
    legal_boundary: str = "This concept provides technical evidence only and does not determine legal proof.",
) -> ProofConcept:
    return ProofConcept(
        concept_id=concept_id,
        display_name=display_name,
        definition=definition,
        category=category,  # type: ignore[arg-type]
        exact_claim=exact_claim,
        subject=subject,
        claim_boundary=boundary,
        required_evidence=evidence,
        verification_procedure=procedure,
        trust_dependencies=trust,
        failure_conditions=failure_conditions,
        verification_capabilities=capabilities,
        known_limitations=limitations,
        privacy_implications=privacy,
        legal_boundary=legal_boundary,
        implementation_maturity=maturity,  # type: ignore[arg-type]
    )


PROOF_CONCEPTS: tuple[ProofConcept, ...] = (
    _concept(
        "integrity",
        "Proof of Integrity",
        "object_and_existence",
        "locally_supported",
        "Assesses whether a current byte object matches a recorded digest state.",
        "The supplied subject bytes match the digest recorded by the proof packet.",
        "A byte object identified by SHA-256 digest.",
        "Digest matches support byte-level integrity only.",
        ("file digest", "manifest identifiers", "packet checks"),
        ("hash supplied bytes", "compare SHA-256 with the recorded manifest digest"),
        ("supplied bytes do not match the recorded digest", "required digest evidence is unavailable"),
        ("Integrity does not establish authenticity, authorship, ownership, or truth.",),
        ("sha256 verification", "packet integrity diagnostics"),
        privacy=("Verification reads the supplied file bytes to calculate a digest.",),
        legal_boundary="Integrity verification is technical byte-state evidence, not legal proof of authorship, ownership, truth, or admissibility.",
    ),
    _concept(
        "existence",
        "Proof of Existence",
        "object_and_existence",
        "locally_supported",
        "Assesses timestamp evidence for a recorded digest.",
        "The recorded subject digest existed within the available timestamp evidence no later than the supported time boundary.",
        "A recorded SHA-256 digest and its timestamp evidence.",
        "Current support is local or imported evidence review, not external anchoring.",
        ("target digest", "local timestamp", "imported receipt metadata"),
        ("inspect timestamping metadata", "verify imported receipt metadata and target digest consistency"),
        ("timestamp evidence is corrupted", "timestamp policy requirements are not met"),
        ("Only local timestamp and imported-receipt handling are currently available; independently verified external timestamping is absent.",),
        ("local_only timestamp inspection", "timestamp receipt integrity checks"),
        trust=("local system clock", "local packet storage", "future external timestamp providers where implemented"),
        privacy=("Timestamp evidence records digest and local timing context but not source file contents.",),
        legal_boundary="Local timestamp evidence can support review but is not authoritative time, external anchoring, legal proof, or proof of content truth.",
    ),
    _concept(
        "records",
        "Proof of Records",
        "records_and_history",
        "locally_supported",
        "Assesses whether a canonical record envelope is present and internally consistent with the packet subject.",
        "A canonical record envelope describing the subject digest and declared metadata is present in the proof packet and remains internally consistent with the packet's recorded subject.",
        "A canonical record envelope bound to a SHA-256 subject digest.",
        "Record envelopes support local record review only and do not prove metadata truth, authority, ownership, identity, authorship, authenticity, or legal validity.",
        ("record descriptor", "canonical record envelope", "subject digest", "records concept claim"),
        ("validate record envelopes", "recompute record IDs", "verify subject binding", "verify records claim linkage"),
        ("record envelope is missing, malformed, inconsistent, or not linked to the claimed subject",),
        ("Declared record metadata is not independently verified for truth, authority, completeness, or legal validity.",),
        ("record envelope validation", "record ID recomputation", "records claim linkage"),
        trust=("local proof packet storage",),
        privacy=("Record attributes are stored in the manifest and may expose declared metadata.",),
        legal_boundary="Proof of Records is technical packet-internal evidence. It does not establish legal status, authority, ownership, identity, authorship, authenticity, or truth.",
    ),
    _concept(
        "custody",
        "Proof of Custody",
        "records_and_history",
        "locally_supported",
        "Assesses a retained, canonical, hash-linked custody-event sequence bound to a packet subject.",
        "The proof packet contains a canonical, hash-linked sequence of declared custody events bound to the recorded subject digest, and the retained sequence is internally consistent.",
        "A retained custody-event sequence and SHA-256 subject digest.",
        "Custody events are declared packet metadata. They do not prove physical possession, verified actor identity, legal custody, ownership, authorship, authenticity, truth, complete history, or immutability.",
        ("custody event descriptors", "canonical custody event envelopes", "event hashes", "previous-event links", "custody concept claim"),
        ("validate custody events", "recompute event hashes and IDs", "verify sequence links", "verify chain head", "verify custody claim linkage"),
        ("custody section is missing, malformed, inconsistent, or not linked to the claimed subject",),
        (
            "Declared actors are not independently verified identities.",
            "Real-world possession, legal custody, transfer, complete history, and event occurrence are not proven.",
            "Declared event times are metadata and are not external timestamp evidence.",
        ),
        ("custody event validation", "hash-link verification", "custody claim linkage"),
        trust=("local proof packet storage",),
        privacy=("Custody actors, locations, references, and attributes are stored in the manifest and may expose sensitive context.",),
        legal_boundary="Proof of Custody is technical packet-internal evidence. It does not establish legal custody, physical possession, actor identity, authority, ownership, authenticity, truth, or admissibility.",
    ),

    _concept(
        "provenance",
        "Proof of Provenance",
        "records_and_history",
        "locally_supported",
        "Assesses retained, canonical declared lineage relationships between a packet subject and parent digests.",
        "The proof packet contains canonical declared lineage relationships binding the recorded subject digest to declared parent digests, and the retained lineage declarations are internally consistent.",
        "A SHA-256 subject digest and declared parent SHA-256 digests.",
        "Provenance edges are declared packet metadata. They do not prove parent file existence, actual derivation, verified origin, authorship, ownership, authenticity, authority, truth, complete lineage, or external registration.",
        ("provenance descriptors", "canonical provenance edge envelopes", "child digest", "parent digests", "provenance concept claim"),
        ("validate provenance edges", "recompute provenance edge IDs", "verify child and parent digest structure", "verify provenance claim linkage"),
        ("provenance section is missing, malformed, inconsistent, or not linked to the claimed subject",),
        (
            "Declared parent digests are not independently verified to exist.",
            "Declared lineage relationships do not prove real-world derivation, origin, authorship, ownership, authenticity, or complete history.",
            "Declared operation, actor, reference, and occurred-time metadata are not externally verified.",
        ),
        ("provenance edge validation", "edge ID recomputation", "provenance claim linkage"),
        trust=("local proof packet storage",),
        privacy=("Provenance descriptors and manifest edges may expose parent digests, operations, actors, references, and attributes.",),
        legal_boundary="Proof of Provenance is technical packet-internal evidence. It does not establish legal status, verified origin, authority, ownership, authorship, authenticity, truth, or admissibility.",
    ),
    _concept(
        "transaction",
        "Proof of Transaction",
        "records_and_history",
        "locally_supported",
        "Assesses retained, canonical declared transaction envelopes bound to a packet subject.",
        "The proof packet contains canonical declared transaction envelopes binding the recorded subject digest to declared participants and transaction metadata, and the retained declarations are internally consistent.",
        "A SHA-256 subject digest and declared transaction participants and metadata.",
        "Transaction envelopes are declared packet metadata. They do not prove transaction occurrence, payment, delivery, participant identity, consent, authority, ownership transfer, legal effect, authenticity, or external registration.",
        ("transaction descriptors", "canonical transaction envelopes", "subject digest", "transaction concept claim"),
        ("validate transaction envelopes", "recompute transaction IDs", "verify subject binding", "verify transaction claim linkage"),
        ("transaction section is missing, malformed, inconsistent, or not linked to the claimed subject",),
        (
            "Declared participants are not independently verified identities.",
            "Transaction occurrence, payment, delivery, consent, authority, ownership transfer, and legal effect are not proven.",
            "Declared occurred_at values are metadata and are not external timestamp evidence.",
        ),
        ("transaction envelope validation", "transaction ID recomputation", "transaction claim linkage"),
        trust=("local proof packet storage",),
        privacy=("Transaction descriptors and manifest envelopes may expose participants, references, terms, and attributes.",),
        legal_boundary="Proof of Transaction is technical packet-internal evidence. It does not establish legal status, consent, authority, ownership transfer, payment, delivery, authenticity, or enforceability.",
    ),
    _concept(
        "identity",
        "Proof of Identity",
        "identity_and_authority",
        "locally_supported",
        "Assesses retained, canonical declared identity assertions bound to a packet subject.",
        "The proof packet contains canonical declared identity assertions binding the recorded subject digest to declared identifiers, and the retained assertions are internally consistent.",
        "A SHA-256 subject digest and declared identity identifiers.",
        "Identity assertions are declared packet metadata. They do not prove identifier ownership, personhood, organisational status, key control, authorship, ownership, authority, consent, authenticity, legal identity, or external validation.",
        ("identity descriptors", "canonical identity assertion envelopes", "subject digest", "identity concept claim"),
        ("validate identity assertions", "recompute assertion IDs", "verify subject binding", "verify identity claim linkage"),
        ("identity section is missing, malformed, inconsistent, or not linked to the claimed subject",),
        (
            "Identifiers are declared and not externally verified.",
            "Identity existence, personhood, organisational status, account ownership, key ownership, and key control are not proven.",
            "Authorship, authority, ownership, consent, authenticity, legal identity, and external validation are not established.",
        ),
        ("identity assertion validation", "assertion ID recomputation", "identity claim linkage"),
        trust=("local proof packet storage",),
        privacy=("Identity descriptors and manifest assertions may expose identifiers, display names, key fingerprints, references, and attributes.",),
        legal_boundary="Proof of Identity is technical packet-internal evidence. It does not establish verified identity, personhood, authority, authorship, ownership, key control, legal identity, or external recognition.",
    ),
    _concept(
        "lineage",
        "Proof of Lineage",
        "records_and_history",
        "locally_supported",
        "Assesses recorded relationships between packet events and amendments.",
        "Recorded events link to prior recorded events or packet identifiers under the local chain model.",
        "Recorded evidence-chain and amendment events.",
        "Only recorded relationships are assessed; completeness of history is not proven.",
        ("event hashes", "previous-event links", "amendment references"),
        ("verify event hashes", "verify previous-event links", "verify amendment references"),
        ("recorded links are broken", "event hashes do not reproduce"),
        ("Only recorded relationships are assessed; completeness of history is not proven.",),
        ("event-chain verification", "amendment lineage checks"),
        trust=("local evidence-chain storage",),
        privacy=("Lineage records may reveal event timing, notes, and relationships.",),
    ),
    _concept(
        "authenticity",
        "Proof of Authenticity",
        "identity_and_authority",
        "modelled",
        "Would assess whether evidence supports a claim that an artefact is authentic under a defined policy.",
        "An artefact is supported as authentic under a defined external policy.",
        "An artefact and external authenticity evidence.",
        "Digest and signature checks support narrower integrity and signer-key claims but do not establish real-world authenticity.",
        ("identity evidence", "authority evidence", "trusted signing policy"),
        ("not executable in this slice",),
        ("required identity, authority, or authenticity evidence is absent"),
        ("Digest and signature checks do not establish real-world authenticity.",),
        privacy=("Authenticity assessment may require identity and authority evidence.",),
    ),
    _concept(
        "ownership",
        "Proof of Ownership",
        "identity_and_authority",
        "modelled",
        "Would assess evidence connecting an artefact or right to an owner under a defined policy.",
        "A party owns or is entitled to a subject under a defined external policy.",
        "An artefact, claimed owner, and entitlement evidence.",
        "Ownership requires identity, authority, entitlement, and jurisdiction-specific external evidence.",
        ("identity evidence", "entitlement evidence", "authority chain"),
        ("not executable in this slice",),
        ("identity, authority, entitlement, or jurisdiction-specific evidence is absent"),
        ("Requires identity, authority, entitlement and jurisdiction-specific external evidence.",),
        privacy=("Ownership assessment may require sensitive identity, entitlement, or legal evidence.",),
    ),
    _concept(
        "reality",
        "Proof of Reality",
        "assessment_and_verification",
        "modelled",
        "Long-term layered assessment of whether evidence supports a claim about real-world origin or transformation.",
        "Layered independent evidence supports a claim about real-world origin or transformation.",
        "An artefact and independent corroborating evidence layers.",
        "There is no current binary or conclusive implementation.",
        ("device attestation", "trusted timestamps", "witness evidence", "custody continuity", "external corroboration"),
        ("not executable in this slice",),
        ("independent corroborating evidence layers are absent or conflicting"),
        ("Long-term layered assessment only; no current binary or conclusive implementation.",),
        trust=("future external attestations", "future corroborating evidence sources"),
        privacy=("Reality assessment may require sensitive context, identity, location, or device evidence.",),
        legal_boundary="Proof of Reality is not implemented as a binary or conclusive legal finding.",
    ),
)

_REGISTRY = {concept.concept_id: concept for concept in PROOF_CONCEPTS}


def concept_registry() -> list[dict[str, object]]:
    return [_REGISTRY[key].to_dict() for key in sorted(_REGISTRY)]


def get_concept(concept_id: str) -> ProofConcept:
    return _REGISTRY[concept_id]
